// styles/theme.js
export const COLORS = {
    orange: "#F57C20",
    orangeLight: "#FFF3E8",
    orangeBg: "#FEF7F0",
    green: "#22C55E",
    greenBg: "#ECFDF5",
    red: "#EF4444",
    redBg: "#FEF2F2",
    bg: "#FAFAFA",
    white: "#fff",
    text: "#1a1a1a",
    textSub: "#333",
    textMuted: "#888",
    textLight: "#999",
    textLighter: "#aaa",
    textPlaceholder: "#bbb",
    textHint: "#ccc",
    border: "#eee",
    divider: "#f0f0f0",
    inputBg: "#f3f3f3",
    cardShadow: "0 2px 20px rgba(0,0,0,.06)",
    listShadow: "0 1px 4px rgba(0,0,0,.04)",
  };